### ISSUE TITLE
Exception: No scan data to process. Check filter_scan_events

### ISSUE THREAD

**Issue by KeironO** [computational-metabolomics/dimspy#36]
I'm experiencing a strange "no scan data to process" error:

Exception: No scan data to process. Check filter_scan_events
```
keo7@keo7-OptiPlex-790:~/Data/dimspy-denisa/mzmlsplits$ dimspy process-scans -i positive.zip -o positive.s -m "median" -s 0.4
Executing dimspy version 1.1.0.
Namespace(block_size=5000, exclude_scan_events=[], filelist=None, function_noise='median', include_scan_events=[], input=['positive.zip'], min_fraction=0.5, min_scans=1, ncpus=None, output='positive.s', ppm=2.0, remove_mz_range=[], report=None, ringing_threshold=None, rsd_threshold=None, skip_stitching=False, snr_threshold=0.4, step='process-scans')

0001-A002-160824-a.mzML
Reading scans....
Traceback (most recent call last):
  File "/home/keo7/VirtualEnvs/pythonnet-build/bin/dimspy", line 11, in <module>
    sys.exit(main())
  File "/home/keo7/VirtualEnvs/pythonnet-build/local/lib/python2.7/site-packages/dimspy/__main__.py", line 443, in main
    ncpus=args.ncpus)
  File "/home/keo7/VirtualEnvs/pythonnet-build/local/lib/python2.7/site-packages/dimspy/tools.py", line 71, in process_scans
    pls_scans = read_scans(filenames[i], source, function_noise, min_scans, filter_scan_events)
  File "/home/keo7/VirtualEnvs/pythonnet-build/local/lib/python2.7/site-packages/dimspy/process/replicate_processing.py", line 111, in read_scans
    raise Exception("No scan data to process. Check filter_scan_events")
Exception: No scan data to process. Check filter_scan_events
```

**Comment by KeironO** [comment]
https://drive.google.com/file/d/16qc2Eaxi-1xHoevOnCqcGNFfEvaRme1k/view?usp=sharing

**Comment by RJMW** [comment]
What instrument was used to collect the data? The instrument model is not listed in your mzML file.

DIMSpy only supports mzML files that are converted from Thermo raw files (using msConvert).

The grouping of replicate scans (for averaging) is based on the "filter string" (MS:1000512) property in the mzML file. Not present in the mzML file you provided. We do have plans to make DIMSpy more flexible and allow data processing for other instrument specific data.

Please, can you also provide us with the (non-converted) raw file?

**Comment by KeironO** [comment]
This sample was processed using a Thermo Scientific Exactive TM Plus Orbitrap, in fast polarity switching mode. I've converted the RAW files into mzML standard ones, before pulling the polarities our using ```xcms``` and then writing to mzml file again using ```mzR```.

Off the top of my head (no computer around me), isn't ```MS:1000512```merely for giving a scan a unique ID? Would it be possible just to refactor the ```mzml_portal.py```to generate a unique identifier in any instance where it doesn't exist?

**Comment by RJMW** [comment]
I assume you are using msConvert to convert the raw files. If so, msconvert does in include the option to filter by polarity. See here (bottom of the page): http://proteowizard.sourceforge.net/tools/filters.html

`--filter "polarity positive"`

**Comment by KeironO** [comment]
Unfortunately the Linux version of proteowizard features zero vendor support (I noticed that you surpassed that issue by using ```pythonnet```), so I've had to do it manually using ```pymzml```.
