### ISSUE TITLE
skip_stitching error message

### ISSUE THREAD

**Issue by nienkevanunen** [computational-metabolomics/dimspy#41]
I believe this should say `set 'skip_stitching' to True` instead of False. 

![image](https://user-images.githubusercontent.com/45174721/60980526-f248e080-a334-11e9-873a-fde0412e104f.png)

**Comment by RJMW** [comment]
Thanks for highlighting.

Fixed in 266a72d2a562bc9de5ee2349a6ca3db99a7ca31c
