### ISSUE TITLE
Running into an error " raise IOError('input database missing crucial attribute [mz]')

### ISSUE THREAD

**Issue by npbhavya** [computational-metabolomics/dimspy#45]
Hi, 

I installed the dimspy as a conda enviornment and when I try to run the command 
"dimspy hdf5-pm-to-txt --input 'MTBLS79__01_262_02_263.hdf5' --output 'test' --delimiter tab --attribute_name intensity --representation-samples rows", the input file is one of the test datasets from git. I am running into the following error 

Namespace(attribute_name='intensity', class_label_rsd=(), comprehensive=False, delimiter='tab', input='MTBLS79__01_262_02_263.hdf5', output='test', representation_samples='rows', step='hdf5-pm-to-txt')
Traceback (most recent call last):
  File "/N/soft/rhel7/dimspy/dimspy-env/bin/dimspy", line 6, in <module>
    sys.exit(dimspy.__main__.main())
  File "/N/soft/rhel7/dimspy/dimspy-env/lib/python2.7/site-packages/dimspy/__main__.py", line 542, in main
    comprehensive=args.comprehensive)
  File "/N/soft/rhel7/dimspy/dimspy-env/lib/python2.7/site-packages/dimspy/tools.py", line 337, in hdf5_peak_matrix_to_txt
    obj = hdf5_portal.load_peak_matrix_from_hdf5(filename)
  File "/N/soft/rhel7/dimspy/dimspy-env/lib/python2.7/site-packages/dimspy/portals/hdf5_portal.py", line 170, in load_peak_matrix_from_hdf5
    raise IOError('input database missing crucial attribute [mz]')
IOError: input database missing crucial attribute [mz]

Any suggestions on how to get past this error?
Thank You, 
Bhavya

**Comment by RJMW** [comment]
Hi @npbhavya 

The hdf5 file you are trying to convert does include a list of peaklists not a peak matrix. Find below two examples of how to convert hdf5 files into txt format using **hdf5-pm-to-txt** (peak matrix) and **hdf5-pls-to-txt** (peaklists).

```
mkdir example
dimspy hdf5-pm-to-txt --input 'MTBLS79_mzml_peak_matrix_sf.hdf5' --output 'example/pm.txt' --delimiter tab --attribute_name intensity --representation-samples rows
```

```
mkdir example
dimspy hdf5-pls-to-txt --input 'MTBLS79__01_262_02_263.hdf5' --output 'test' --delimiter tab
```

**Comment by npbhavya** [comment]
Thank you, that did the trick.  I was trying with the incorrect hdf5 file.
