### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by KeironO** [computational-metabolomics/dimspy#46]
I'm looking to cite this package, but am unable to find any documentation on where and what citation I should use.

**Comment by RJMW** [comment]
Hi @KeironO 

Sorry for not replying to your question sooner!

We are pleased to announce the release of DIMSpy [v2.0.0](https://github.com/computational-metabolomics/dimspy/releases/tag/v2.0.0), including more extensive [documentation](https://dimspy.readthedocs.io/en/latest). We have also included a page on how to [cite](https://dimspy.readthedocs.io/en/latest/citation.html) DIMSpy.

Feel free to contact me if you need any further information.
