### ISSUE TITLE
Installation on python3+

### ISSUE THREAD

**Issue by satish5577** [computational-metabolomics/dimspy#58]
Hi, I am trying installing on python3 but still its throwing an error 2.7.8 required, is it still necessary to install it on 2.7?

**Comment by RJMW** [comment]
Hi @satish5577

We are pleased to announce the release of DIMSpy [v2.0.0](https://github.com/computational-metabolomics/dimspy/releases/tag/v2.0.0). This version is compatible with python ≥3.7.

Please, give it a go and feel free to contact me if you need any further information.
